"""Skill scaffolding utilities for ``cue-agent create-skill``."""

from __future__ import annotations

import re
from pathlib import Path


def normalize_skill_name(raw_name: str) -> str:
    """Convert a raw skill name into a safe snake_case module/folder name."""
    name = raw_name.strip().lower().replace("-", "_").replace(" ", "_")
    name = re.sub(r"[^a-z0-9_]", "", name)
    name = re.sub(r"_+", "_", name).strip("_")
    if not name:
        raise ValueError("Skill name must contain at least one letter or number")
    if name[0].isdigit():
        name = f"skill_{name}"
    return name


def create_skill_scaffold(
    name: str,
    *,
    skills_dir: str = "skills",
    style: str = "pack",
    force: bool = False,
) -> Path:
    """Create a new skill scaffold and return the created entry path."""
    skill_name = normalize_skill_name(name)
    root = Path(skills_dir).expanduser()
    root.mkdir(parents=True, exist_ok=True)

    if style == "simple":
        target = root / f"{skill_name}.py"
        if target.exists() and not force:
            raise FileExistsError(f"{target} already exists (use --force to overwrite)")
        target.write_text(_simple_skill_template(skill_name), encoding="utf-8")
        return target

    if style == "pack":
        target = root / skill_name
        if target.exists() and not force:
            raise FileExistsError(f"{target} already exists (use --force to overwrite)")
        target.mkdir(parents=True, exist_ok=True)
        (target / "skill.py").write_text(_pack_skill_template(skill_name), encoding="utf-8")
        (target / "prompt.md").write_text(_prompt_template(skill_name), encoding="utf-8")
        (target / "config.yaml").write_text(_config_template(), encoding="utf-8")
        (target / "README.md").write_text(_pack_readme_template(skill_name), encoding="utf-8")
        return target

    raise ValueError(f"Unsupported scaffold style: {style}")


def _simple_skill_template(skill_name: str) -> str:
    return f'''"""Generated CueAgent skill: {skill_name}."""

from __future__ import annotations


SKILL_MANIFEST = {{
    "name": "{skill_name}",
    "description": "Describe what this skill does.",
    "tools": [
        {{
            "name": "run",
            "schema": {{
                "name": "run",
                "parameters": {{
                    "type": "object",
                    "properties": {{
                        "input": {{
                            "type": "string",
                            "description": "Primary input text for this skill",
                        }}
                    }},
                    "required": ["input"],
                    "additionalProperties": False,
                }},
            }},
        }}
    ],
}}


def run(input: str) -> dict:
    """Main entry point for the generated skill."""
    return {{
        "skill": "{skill_name}",
        "input": input,
        "result": "todo",
    }}
'''


def _pack_skill_template(skill_name: str) -> str:
    return f'''"""Generated CueAgent skill pack: {skill_name}."""

from __future__ import annotations


SKILL_MANIFEST = {{
    "name": "{skill_name}",
    "description": "Describe what this skill pack does.",
    "tools": [
        {{
            "name": "run",
            "schema": {{
                "name": "run",
                "parameters": {{
                    "type": "object",
                    "properties": {{
                        "task": {{
                            "type": "string",
                            "description": "Task request for the skill",
                        }},
                        "priority": {{
                            "type": "string",
                            "description": "Optional task priority (low/medium/high)",
                        }},
                    }},
                    "required": ["task"],
                    "additionalProperties": False,
                }},
            }},
        }}
    ],
}}


def run(task: str, priority: str = "medium") -> dict:
    """Main entry point for the generated skill."""
    return {{
        "skill": "{skill_name}",
        "task": task,
        "priority": priority,
        "status": "todo",
    }}
'''


def _prompt_template(skill_name: str) -> str:
    return f"""# {skill_name} system prompt

You are the `{skill_name}` skill.

Goals:
- Be concise and factual
- Return deterministic, machine-readable output where possible
- Flag uncertainty explicitly
"""


def _config_template() -> str:
    return """# Skill-local configuration values
endpoint: https://api.example.com
timeout_seconds: 15
"""


def _pack_readme_template(skill_name: str) -> str:
    return f"""# {skill_name}

Generated by `cue-agent create-skill`.

Files:
- `skill.py` — tool manifest and Python functions
- `prompt.md` — optional skill system prompt (auto-loaded)
- `config.yaml` — optional skill config key/values (auto-loaded)
"""
